<a href="https://colab.research.google.com/github/PrateekCoder/Recommendation-Systems/blob/main/Content_Based_Movie_Recommendation_System_Using_LSA_Dimensionality_Reduction_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import all the required packages
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
#Import the imdb movies dataset
df = pd.read_csv('imdb_movie_data.csv')

In [ ]:
df

,Unnamed: 0,index,tconst,titleType,Title,Year,runtimeMinutes,genres,directors,writers,averageRating,numVotes,actors,Movie
0,0,16917,tt0035423,movie,Kate & Leopold,2001,118.0,"Comedy,Fantasy,Romance",James Mangold,"Steven Rogers, James Mangold",6.4,86032,"Hugh Jackman, Meg Ryan, Breckin Meyer, Liev Sc...",Kate & Leopold (2001)
1,1,38887,tt0062336,movie,The Tango of the Widower and Its Distorting Mi...,2020,70.0,Drama,"Raúl Ruiz, Valeria Sarmiento","Raúl Ruiz, Omar Saavedra Santis",6.4,164,"Claudia Paz, Rubén Sotoconil, Shenda Román, Lu...",The Tango of the Widower and Its Distorting Mi...
2,2,44457,tt0069049,movie,The Other Side of the Wind,2018,122.0,Drama,Orson Welles,"Orson Welles, Oja Kodar",6.7,7565,"John Huston, Peter Bogdanovich, Susan Strasber...",The Other Side of the Wind (2018)
3,3,53246,tt0079644,movie,November 1828,2001,140.0,"Drama,War",Teguh Karya,Teguh Karya,6.8,214,"Rachmat Hidayat, El Manik, Soerip, Jenny Rachm...",November 1828 (2001)
4,4,60711,tt0088751,movie,The Naked Monster,2005,100.0,"Comedy,Horror,Sci-Fi","Wayne Berwick, Ted Newsom",Ted Newsom,5.2,329,"John Goodwin, R.G. Wilson, Kenneth Tobey, Brin...",The Naked Monster (2005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131249,131249,1004968,tt9916270,movie,Il talento del calabrone,2020,84.0,Thriller,Giacomo Cimini,"Giacomo Cimini, Lorenzo Collalti",5.8,1394,"Sergio Castellitto, Lorenzo Richelmy, Anna Fog...",Il talento del calabrone (2020)
131250,131250,1004971,tt9916362,movie,Coven,2020,92.0,"Drama,History",Pablo Agüero,"Pablo Agüero, Katell Guillou",6.4,5182,"Amaia Aberasturi, Daniel Fanego, Garazi Urkola...",Coven (2020)
131251,131251,1004974,tt9916428,movie,The Secret of China,2019,NaN,"Adventure,History,War",Jixing Wang,\N,3.8,14,"Wang Peng Kai, Valery Gadreau, Wenli Jiang, Vi...",The Secret of China (2019)
131252,131252,1004979,tt9916538,movie,Kuambil Lagi Hatiku,2019,123.0,Drama,Azhar Kinoi Lubis,"Arief Ash Siddiq, Rino Sarjono, Salman Aristo",8.3,6,"Lala Karmela, Cut Mini Theo, Ria Irawan, Sahil...",Kuambil Lagi Hatiku (2019)
131253,131253,1004990,tt9916730,movie,6 Gunn,2017,116.0,NaN,Kiran Gawade,Kiran Gawade,8.3,10,"Bhushan Pradhan, Ganesh Vasant Patil, Sunil Ba...",6 Gunn (2017)

In [ ]:
# Combine movie name and tags into a single string
df['content'] = df['Movie'].astype(str) + ' ' + df['runtimeMinutes'].astype(str) + ' ' + df['genres'] + ' ' + df['directors'] + ' ' + df['writers'] + ' ' + df['averageRating'].astype(str) + ' ' + df['numVotes'].astype(str) + df['actors'].astype(str)
df['content'] = df['content'].fillna('')

In [ ]:
# Create bag of words
vectorizer = CountVectorizer()
bow = vectorizer.fit_transform(df['content'])

In [ ]:
# Convert bag of words to TF-IDF
tfidf_transformer = TfidfTransformer()
tfidf = tfidf_transformer.fit_transform(bow)

In [ ]:
# Apply LSA or LSI
lsa = TruncatedSVD(n_components=100, algorithm='arpack')
lsa.fit(tfidf)

TruncatedSVD(algorithm='arpack', n_components=100)

In [ ]:
# Get the user input
user_movie = input("Enter a movie title: ")

Enter a movie title: The Prestige (2006)

In [ ]:
# Find the index of the user movie
movie_index = df[df['Movie'] == user_movie].index[0]

# Compute the cosine similarities between the user movie and all other movies
similarity_scores = cosine_similarity(tfidf[movie_index], tfidf)

# Get the top 10 most similar movies
similar_movies = list(enumerate(similarity_scores[0]))
sorted_similar_movies = sorted(similar_movies, key=lambda x: x[1], reverse=True)[1:20]

# Print the top 10 similar movies
for i, score in sorted_similar_movies:
    print("{}: {}".format(i, df.loc[i, 'Movie']))

17830: The Dark Knight (2008)
44912: The Dark Knight Rises (2012)
21896: Interstellar (2014)
993: Memento (2000)
10527: Batman Begins (2005)
115499: Tenet (2020)
46363: Inception (2010)
103035: Dunkirk (2017)
59251: I Kissed a Vampire (2010)
76235: No Way Out But One (2011)
47516: Broken Contact: A Poltergeist Story (2020)
40126: Memories of Reality (2021)
97983: Pause of the Clock (2015)
1782: Dr. Benny (2003)
20624: Man of Steel (2013)
4081: Insomnia (2002)
102831: Turn in Your Grave (2012)
32090: Montana (2008)
9361: Meridian (2002)